### ISSUE TITLE
gradio/marqo dependency conflict with urllib3

### ISSUE THREAD

**Issue by normal-coder** [Storia-AI/repo2vec#16]
## Environment

- System: macOS 15
- Python: 3.10.13
- pip: 24.4

## Problems

With `pip install -r requirements.txt` it fails due to a conflict

```bash
~ pip install -r requirements.txt
...
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting langchain-core<0.3.0,>=0.2.32 (from langchain==0.2.14->-r requirements.txt (line 4))
  Using cached langchain_core-0.2.36-py3-none-any.whl.metadata (6.2 kB)
Collecting ollama<1,>=0.3.0 (from langchain-ollama==0.1.2->-r requirements.txt (line 7))
  Using cached ollama-0.3.2-py3-none-any.whl.metadata (3.8 kB)
INFO: pip is looking at multiple versions of marqo to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 3) and -r requirements.txt (line 9) because these package versions have conflicting dependencies.

The conflict is caused by:
    gradio 4.42.0 depends on urllib3~=2.0
    marqo 3.7.0 depends on urllib3<2.0.0 and >=1.26.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by friofry** [comment]
As a temporary workaround, I've removed versions in requirements.txt 
```
GitPython==3.1.43
Pygments==2.18.0
gradio
langchain==0.2.14
langchain-community==0.2.12
langchain-anthropic==0.1.23
langchain-ollama==0.1.2
langchain-openai==0.1.22
marqo
nbformat==5.10.4
openai==1.42.0
pinecone==5.0.1
python-dotenv==1.0.1
requests==2.32.3
semchunk==2.2.0
tiktoken==0.7.0
tree-sitter==0.22.3
tree-sitter-language-pack==0.2.0
```
And it worked, with dependencies. But then it failed on `Pinecone.from_existing_index`.

So I rolled back to `git reset --hard d2247dd`. Everything works like a charm :)

**Comment by normal-coder** [comment]
Everything works fine under `gradio-4.26.0`. I commented out `gradio` from `requirements.txt` and installed dependencies using `pip install -r requirements.txt gradio`.

**Comment by normal-coder** [comment]
> As a temporary workaround, I've removed versions in requirements.txt
> 
> ```
> GitPython==3.1.43
> Pygments==2.18.0
> gradio
> langchain==0.2.14
> langchain-community==0.2.12
> langchain-anthropic==0.1.23
> langchain-ollama==0.1.2
> langchain-openai==0.1.22
> marqo
> nbformat==5.10.4
> openai==1.42.0
> pinecone==5.0.1
> python-dotenv==1.0.1
> requests==2.32.3
> semchunk==2.2.0
> tiktoken==0.7.0
> tree-sitter==0.22.3
> tree-sitter-language-pack==0.2.0
> ```
> 
> And it worked, with dependencies. But then it failed on `Pinecone.from_existing_index`.
> 
> So I rolled back to `git reset --hard d2247dd`. Everything works like a charm :)

This doesn't look like a good idea. Because I've just tried using Ollama 🤣
